const core = require('@actions/core');
const github = require('@actions/github');
const fs = require('fs');
const fetch = require('node-fetch');


try {
let payloadFile = fs.readFileSync('src/analytics-autogenerated/plan.json');
let payloadJSON = JSON.parse(payloadFile);
delete payloadJSON["name"];
delete payloadJSON["create_time"];
delete payloadJSON["update_time"];

let newJSON = {};
newJSON["update_mask"] = {
    "paths": [
      "tracking_plan.display_name",
      "tracking_plan.rules"
    ]
  };
newJSON["tracking_plan"] = payloadJSON;
var json = JSON.stringify(newJSON);

var requestOptions = {
    method: 'PUT',
    headers: {
        'Authorization': 'Bearer lz76O8KXwjMeYnnvk3aKlCas721IFP-7x2V7s_oN8kc.DwF1Wi8UGqZ12AbVJFXY_Aa7ebBBUiCdXwXUiyy8xvk',
        'Content-Type': 'application/json'
      },
    body: json
  };
  
  const response = fetch("https://platform.segmentapis.com/v1beta/workspaces/protocols-diffs/tracking-plans/rs_21k7cGxAiOsvxfxBMXdR2Z1iOGr", requestOptions)
    .then(response => response.text())
    .then(result => console.log(result))
    .catch(error => console.log('error', error));

} catch (error) {
  core.setFailed(error.message);
}