
   
on:
  workflow_dispatch:
jobs:
  configAPI_update:
    runs-on: ubuntu-latest
    name: Update Dev Tracking Plan
    steps:
      - name: Config API Action
        id: hello
        uses: rishnair/javascript-action@v1
        