name: Update plan.json and create branch

on:
  repository_dispatch:
    types:
      - tracking_plan_updated

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - name: Hello World
      run: echo "Hello World"
    - name: Create branch
      uses: peterjgrainger/action-create-branch@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        branch: ${{ github.run_id }}
    - name: Checkout branch
      uses: actions/checkout@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        ref: ${{ github.run_id }}
    - name: Commit Update Tracking Plan
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SEGMENT_CONFIG_API_TOKEN: ${{ secrets.SEGMENT_CONFIG_API_TOKEN }}
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        npx typewriter update
        git add .
        git commit -m "regenerated plan.json"
        git push